# Utilisez l'image de base Python
FROM python:3.8-slim-buster

# Répertoire de travail dans le conteneur
WORKDIR /serveur_rest

COPY serveur_rest/requirements.txt /serveur_rest/

# Installez les dépendances
RUN pip install --no-cache-dir -r requirements.txt

# Exposez le port 5001
EXPOSE 5001

VOLUME [ "/serveur_rest" ]

# Commande pour exécuter l'application
CMD [ "python3", "serveur.py" ]